### ISSUE TITLE
openlab.php must be moved out of plugin

### ISSUE THREAD

**Issue by boonebgorges** [openlab-at-city-tech/webworkqa#163]

**Comment by boonebgorges** [comment]
This is now done. Testing will involve looking at the two bits of functionality that have been moved, specifically:

1. The 'Faculty' and 'Student' labels that appear next to user avatars
2. "Admin" access should be granted to OL users with the Faculty user type

**Comment by bree-z** [comment]
Thanks, Boone! Issue 1 looks good. 

Regarding 2, to test this, I invited the testfaculty user to join the group. After joining, that user is listed as a member of the group, and an author on https://openlab.citytech.cuny.edu/ol-webwork/ . It looks like the OpenLab is running version 1.0 of the WeBWorK Q&A plugin, which is the same as the test site.

**Comment by boonebgorges** [comment]
Thanks, Bree. The version numbers don't mean much, but I've just checked and it looks like the production ol-webwork site is running a version of the plugin close enough that it should have the "user-promotion" feature.

What you should be checking for is not the user role on ol-webwork. Instead, Faculty users on the OpenLab should have admin-level access to webworkqa content. For example, when you see 'Question from a Student', users with admin-level access should be able to hover and see the user's display name. Another admin-only feature is the "Incomplete question? The student will be notified and the default reply posted." checkbox when responding to a question.

**Comment by bree-z** [comment]
Thanks Boone. This looks good. I tested with the testfaculty account, which is not a member of the ol-ww group. I was able to hover and see student display names for anonymous questions and was also able to use the "Incomplete question" checkbox.

**Comment by bree-z** [comment]
Hi @boonebgorges , 

I just wanted to check in about user roles on CBOX OL. Should I see the same thing you described [above](https://github.com/openlab-at-city-tech/webworkqa/issues/163#issuecomment-908313920) for the OpenLab in CBOX OL? That is:

> Faculty users on the OpenLab should have admin-level access to webworkqa content. For example, when you see 'Question from a Student', users with admin-level access should be able to hover and see the user's display name. Another admin-only feature is the "Incomplete question? The student will be notified and the default reply posted." checkbox when responding to a question.

Currently, I only see this with the faculty user (testfaculty) that is also the site admin. If what I see is correct, then we'll want to advise people to add any faculty responding to questions on the site as admins -- is that correct?

Thanks!

**Comment by boonebgorges** [comment]
> Currently, I only see this with the faculty user (testfaculty) that is also the site admin. If what I see is correct, then we'll want to advise people to add any faculty responding to questions on the site as admins -- is that correct?

What you see is correct. We don't know ahead of time how CBOX-OL users will set up their member types, so we can't grant access based on member type. Moreover, the OL setup gives admin-level access to *all* Faculty, which is almost certainly too broad for most CBOX-OL sites. As you suggest, manual promotion of users to Administrator will be necessary.

**Comment by bree-z** [comment]
Got it, thanks Boone!
