### ISSUE TITLE
Library ID should not be parsed from the problem text

### ISSUE THREAD

**Issue by boonebgorges** [openlab-at-city-tech/webworkqa#169]
See https://github.com/livinglab/webwork-for-wordpress/issues/119#issuecomment-505097865

After https://github.com/livinglab/webwork-for-wordpress/issues/119#issuecomment-447477832, `problemSource` is part of the POST data that comes from WeBWorK. This, should be used to identify the Library ID, instead of parsing from the content.

This is a pretty easy technical change, but before making it, I want us to be collectively clear about how/whether WeBWorK must be configured to send the `problemSource` data. I'm not 100% sure whether the mods made by @drdrew42 are hotfixes to his specific WW installations, or whether they're improvement that have been accepted by the WW team and included in the release version of the software, or something in between those two.

**Comment by drdrew42** [comment]
So far, my modifications to send more POST data *are only local changes*. 

I will put these into a PR for the WW team for the next release.

Best case scenario, I think, is that we look for the `libraryID` in both places -- because not all WW installations stay up to date. This means outdated WW versions will still default to sending the libraryID in the body of the problem, and updated WW versions will send it separately in the POST.

**Comment by boonebgorges** [comment]
Yes, the same thing had occurred to me (look first for `problemSource`). Please keep me apprised with the progress of the WW PR!

**Comment by drdrew42** [comment]
https://github.com/openwebwork/webwork2/pull/957

**Comment by drdrew42** [comment]
Updated PR on the WeBWorK side, some key names may have changed slightly.

openwebwork/webwork2#986

Note that the following key-values have been added to the POST package:
* $_POST['emailableURL'] => `http://localhost/webwork2/CourseID/problemSetName/problemNumber/?showOldAnswers=1&effectiveUser=student&displayMode=MathJax`
    (this was the only thing instructors missed about the email instructor button - we bring it along so that the Q&A site can include it with the notification email)
* $_POST['randomSeed'] => `2013` 
    (not used yet, but may be useful in re-rendering the student's problem -- via XMLRPC -- instead of decoding the pg64 string that gets sent. This is more for the WeBWorK side, if someone develops a similar replacement for the email instructor button and wants to use this alternate strategy.)
* $_POST['notifyAddresses'] => `Administrator <fake@email.com>;"Prof. Lastname" <lastname@uni.edu>`
    (semicolon delimited list of all users who have permission to receive feedback emails and should be notified when a question is asked)
* $_POST['problemPath'] => `local/folder/some-problem.pg`
    (this is our unique ID for problems)
* $_POST['studentName'] => `Full Name` of the active user
    (This is the student's name in WeBWorK, so that OpenLab can notify the professor with the student's actual name by email - without displaying it publicly if the student chose to remain anonymous)

**Comment by drdrew42** [comment]
#162 used `emailURL` which has now been renamed `emailableURL` and there is perhaps another change from `name` to `studentName`

This issue, #169, uses `problemPath` to take the place of `problemSource` - in providing a value for our `libraryID`

#119 should use `notifyAddresses` for sending out notifications when a question is asked

**Comment by boonebgorges** [comment]
Thanks for your continued work on this, @drdrew42.

I've made some changes so that the plugin now recognizes and stores the new values that you're sending over.

Importantly for the purposes of this ticket, the `problemPath` variable is now being relied on for `libraryID`. If `problemPath` is not available, the plugin tries to pull the path out of the problem content, as things worked originally.

I'm moving this to "testing" status with the caveat that we shouldn't begin any testing until we've confirmed with each other that the WW-Dev (and CT production WW server, when we launch for Spring) are running the most recent patched versions of WeBWorK.

**Comment by drdrew42** [comment]
Will do. Thanks for your work on this as well - I’ll update early next week and confirm here. Then testing can begin whenever is convenient.

**Comment by drdrew42** [comment]
This is a note to myself that ~~a second course will need to be created in WW~~ I will need to spin up a VM with WW-2.14 to test that the "old" way still works, for those WW installations that may not have updated to WW-2.15 (and won't have the expanded set of key-value pairs).

**Comment by bree-z** [comment]
Hi Boone - I think this looks good. Just to confirm, I just asked four questions from Functions - Difference Quotient: Problem 1 (http://146.111.135.122/webwork2/WW-Dev/Functions_-_Difference_Quotient/1). They have the following URLs on the test site:

https://hardg.com/webwork/#:problemId=CUNY/CityTech/Precalculus/setDifference_Quotient/intro-diff-quot.pg:questionId=28
https://hardg.com/webwork/#:problemId=CUNY/CityTech/Precalculus/setDifference_Quotient/intro-diff-quot.pg:questionId=29
https://hardg.com/webwork/#:problemId=CUNY/CityTech/Precalculus/setDifference_Quotient/intro-diff-quot.pg:questionId=30
https://hardg.com/webwork/#:problemId=CUNY/CityTech/Precalculus/setDifference_Quotient/intro-diff-quot.pg:questionId=31

Thanks!

**Comment by boonebgorges** [comment]
Yup, it looks like it's working. Thank you!
