### ISSUE TITLE
webwork_post_data should be stored with 'autoload' = false

### ISSUE THREAD

**Issue by boonebgorges** [openlab-at-city-tech/webworkqa#193]
Ran into a problem on the City Tech OpenLab where `wp_load_alloptions()` was hitting a memory ceiling, due to the very large content of `webwork_post_data_` options. It's worth exploring improved cleanup procedures for these post keys, but in the meantime, they should be set as `autoload=false` to avoid this specific problem.

**Comment by drdrew42** [comment]
Is this a byproduct of the base64 encoded HTML for the problem? 

I wouldn't think that the rest of the contents being submitted would amount to very much data...

**Comment by boonebgorges** [comment]
Yes, that's what's causing the bloat. There were thousands of entries on the production site. I'll open a separate issue to find ways to ensure more timely cleanup.
