### ISSUE TITLE
Clicking on 'Respond to this Question' leads to 404

### ISSUE THREAD

**Issue by bree-z** [openlab-at-city-tech/webworkqa#209]
When I click on 'Respond to this Question' as a non-authenticated user, I get a 404 error rather than being prompted to log in. The URL of the 404 is:  https://hardg.com/webwork/webwork/wp-login.php?redirect_to=/webwork/#:problemId=CUNY/CityTech/Precalculus/setDifference_Quotient/intro-diff-quot.pg:questionId=31

This happens both from the list and single views.

**Comment by boonebgorges** [comment]
@drdrew42 It sounds like the configuration on your end is adding an extra /webwork/. Can you take that out?

**Comment by bree-z** [comment]
Just wanted to ping this, as it's still an issue on hardg.com/webwork. 

Thanks!

**Comment by drdrew42** [comment]
Ive got the url set to `https://hardg.com/webwork/?webwork=1` is that not correct?

**Comment by boonebgorges** [comment]
@bree-z Can you please share a link to a WW problem exhibiting the problem so that I can do some testing?

**Comment by boonebgorges** [comment]
@bree-z Can you please link to the *WeBWorK* problem where you're originating so that I can test the entire flow?

**Comment by boonebgorges** [comment]
Thanks for clarifying. I guess I didn't read your initial question clearly enough.

I've put a fix in place for this.

**Comment by bree-z** [comment]
Thanks Boone. This looks good!

I'm now prompted to log in, and after logging in I'm taken to the question page.
