### ISSUE TITLE
Styling for links is different on non-WeBWorK Q&A pages

### ISSUE THREAD

**Issue by bree-z** [openlab-at-city-tech/webworkqa#211]
Hi Boone, 

Sorry to miss this earlier. On pages without the [webwork] shortcode, the styling for links is different than the Q&A page. 

For example: http://hardg.com/webwork/sample-page/

The links and buttons are green rather than blue. And there's no underline on hover for links in the menu.

**Sample Page:**

<img width="1115" alt="SamplePageLinkStyling" src="https://user-images.githubusercontent.com/7189824/134160308-0b98de00-2aa6-4602-9942-65dd9588583a.png">

**WeBWorK Page:**

<img width="1134" alt="WebworkPageLinkStyling" src="https://user-images.githubusercontent.com/7189824/134160030-19906da2-acf3-4cd3-9d13-235da43e3846.png">

**Comment by boonebgorges** [comment]
I've made changes that address these specific issues. See http://hardg.com/webwork/sample-page/

**Comment by bree-z** [comment]
Thanks Boone. This looks good!
