### ISSUE TITLE
CBOX OL: 'Post this question anonymously' text doesn't wrap correctly

### ISSUE THREAD

**Issue by bree-z** [openlab-at-city-tech/webworkqa#212]
Compare https://openlabdev.commonsinabox.org/webwork-qa-plugin-testing/ with https://hardg.com/webwork/:

**CBOX OL:**

<img width="795" alt="Screen Shot 2021-09-21 at 1 48 34 AM" src="https://user-images.githubusercontent.com/7189824/134200973-bd1106d1-0ca8-4d62-8102-3820e7606cd8.png">

**hardg.com:**

<img width="807" alt="Screen Shot 2021-09-21 at 1 58 33 AM" src="https://user-images.githubusercontent.com/7189824/134201016-5dc034ca-1f79-4642-b73a-91999de4c232.png">

**Comment by boonebgorges** [comment]
The Hemingway parent theme changed its CSS so that we need additional specificity to override. I've made the change.

**Comment by bree-z** [comment]
This is also fixed, thanks!
