### ISSUE TITLE
Hover for the follow/unfollow link differs on CBOX OL and hardg.com/webwork

### ISSUE THREAD

**Issue by bree-z** [openlab-at-city-tech/webworkqa#213]
**CBOX OL:**

<img width="1079" alt="Screen Shot 2021-09-21 at 11 36 37 AM" src="https://user-images.githubusercontent.com/7189824/134202129-75d66f6a-e826-41d6-8fb8-2a256158bcc2.png">

**hardg.com:**

<img width="1134" alt="Screen Shot 2021-09-21 at 11 35 11 AM" src="https://user-images.githubusercontent.com/7189824/134202154-b8786e1c-aae4-4a4e-9b2e-7b469aea57ec.png">

**Comment by boonebgorges** [comment]
This is due to another Hemingway change.

**Comment by bree-z** [comment]
Thanks, Boone. I don't see these changes on the CBOX OL test site after a hard refresh.

**Comment by boonebgorges** [comment]
I'd pulled the latest to hardg.com but not to openlabdev.commonsinabox.org. I've fixed this.

**Comment by bree-z** [comment]
Aha. Got it. This looks good, thanks!
