### ISSUE TITLE
Extra forward slash appears in menu

### ISSUE THREAD

**Issue by bree-z** [openlab-at-city-tech/webworkqa#216]
There's an extra forward slash that appears in the menu before the first menu item.

I'm seeing this on both CBOX OL and hardg.com/webwork. 

<img width="815" alt="ExtraForwardSlash" src="https://user-images.githubusercontent.com/7189824/134401176-fbc5d3e6-5714-40ed-acb4-27fa00654668.png">

**Comment by boonebgorges** [comment]
We were creating this with CSS for some reason. I'm not sure what the reason was. I've removed it.

**Comment by bree-z** [comment]
Thanks Boone, this looks good!
